#name: dreams_mimb
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  - python=3.11
#  - pip
#  - jupyterlab
#  - ipywidgets
#  - notebook
#  - pytorch==2.3.0
#  - pip:
#    - git+https://github.com/pluskal-lab/DreaMS.git
#    - massspecgym
#    - hydra-core
#    - omegaconf



name: dreams_mimb
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # core environment
  - python=3.11
  - pip
  - jupyterlab
  - notebook
  - ipywidgets

  # conda-installable shared libs
  - numpy=1.24.4
  - numba=0.57.1
  - pytorch=2.3.0
  - pytorch-lightning=2.2.5
  - torchmetrics=1.4.0
  - pandas=2.2.1
  - pyarrow=15.0.2
  - h5py=3.11.0
  - rdkit=2023.9.5
  - umap-learn=0.5.6
  - seaborn=0.13.2
  - plotly
  - ase=3.22.1
  - pyopenms
  - hydra-core
  - omegaconf

  # pip-only (no-deps) installs
  - pip:
    - igraph==0.11.4
    - molplotly==1.1.7
    - wandb==0.17.0
    - matchms==0.26.2
    - myopic-mces==1.0.0
    - chemparse==0.3.1
    - chemformula==1.3.1
    - networkx==3.3
    - selfies==2.1.2
    - pulp==2.9.0
    - torch-geometric==2.5.3
    - tokenizers==0.19.1
    - huggingface-hub==0.24.5
    - git+https://github.com/pluskal-lab/DreaMS.git --no-deps
    - massspecgym --no-deps