name: dreams_mimb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipywidgets
  - notebook
  - pytorch>=2.2.1
  - pip:
    - git+https://github.com/pluskal-lab/DreaMS.git
    - massspecgym
    - hydra-core
    - omegaconf