wandb_version: 1

data:
  desc: null
  value:
    mgf_path: data/massspecgym/MassSpecGym.mgf
    labeled_mgf: data/massspecgym/MassSpecGym_chlorine.mgf
    label_element: Cl
    transform:
      _target_: massspecgym.data.transforms.SpecTokenizer
      n_peaks: 64
    dataset:
      _target_: benchmark.data.datasets.BinaryDetectionDataset
      pth: data/massspecgym/MassSpecGym_chlorine.mgf
      spec_transform:
        _target_: massspecgym.data.transforms.SpecTokenizer
        n_peaks: 64
    datamodule:
      _target_: benchmark.data.data_module.BenchmarkDataModule
      dataset:
        _target_: benchmark.data.datasets.BinaryDetectionDataset
        pth: data/massspecgym/MassSpecGym_chlorine.mgf
        spec_transform:
          _target_: massspecgym.data.transforms.SpecTokenizer
          n_peaks: 64
      batch_size: 64
      num_workers: 0
model:
  desc: null
  value:
    name: lit_classifier
    hparams:
      ckpt_path: data/model_checkpoints/ssl_model.ckpt
      num_classes: 2
      n_highest_peaks: 64
      lr: 1.0e-05
      dropout: 0.1
      train_encoder: true
      use_focal: true
      gamma: 0.5
      alpha: 0.8
      pos_weight: null
trainer:
  desc: null
  value:
    _target_: pytorch_lightning.Trainer
    max_epochs: 1
    gradient_clip_val: 0.5
    precision: 16
logger:
  desc: null
  value:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: DreaMS_MIMB
    entity: jozefov-iocb-prague
    name: chlorine_experiment_01
    config: configs/test_config.yaml
callbacks:
  desc: null
  value:
    checkpoint:
      monitor: val_loss
      mode: min
      save_top_k: 1
      dirpath: checkpoints
    lr_monitor:
      logging_interval: step
_wandb:
  desc: null
  value:
    python_version: 3.11.13
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1753862565
    t:
      1:
      - 1
      - 5
      - 9
      - 49
      - 50
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 49
      - 50
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 16
      - 23
      - 66
      4: 3.11.13
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
ckpt_path:
  desc: null
  value: /Users/macbook/CODE/DreaMS_MIMB/data/model_checkpoints/ssl_model.ckpt
num_classes:
  desc: null
  value: 2
n_highest_peaks:
  desc: null
  value: 64
lr:
  desc: null
  value: 1.0e-05
dropout:
  desc: null
  value: 0.1
train_encoder:
  desc: null
  value: true
use_focal:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.5
alpha:
  desc: null
  value: 0.8
pos_weight:
  desc: null
  value: null
